[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --production"]

[phases.build]
cmds = ["cd client && npm install && npm run build"]

[start]
cmd = "NODE_ENV=production node server/index.js"
